# action.yml
name: 'Coligo Action'
description: 'Deploy an application to coligo'

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  
