# action.yml
name: 'Coligo Action'
description: 'Deploy an application to coligo'
inputs:
  project:  # id of input
    description: 'The name of the coligo project'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project }}
